services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-mms-green
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/html:ro
    depends_on:
      - php
    restart: unless-stopped

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php-fpm-mms-green
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    env_file:
      - .env.production
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: postgres-mms-green
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_green:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  postgres_data_green:
