services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-mms
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/html:ro
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php-fpm-mms
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: postgres-mms
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
